try:
    print()

except Exception as ex:
    print("Exception", ex)

finally:
    print("finally")
    